### ISSUE TITLE
Error upon `from scprint import scPrint`

### ISSUE THREAD

**Issue by frenkiboy** [cantinilab/scPRINT#1]
When I run 

`from scprint import scPrint`

I get the following error:

`ImproperlyConfigured: Requested setting INSTALLED_APPS, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.`

The library was installed per instructions.

**Comment by kavithakrishna1** [comment]
Having the same error ^

**Comment by jkobject** [comment]
Hello, It seems to me to be the same error as here:
https://github.com/jkobject/scPRINT/issues/8

let me know but it seems you need to create a lamin account, init a lamin instance and then populate ontologies

**Comment by jkobject** [comment]
I have updated the readme to reflect those tasks.

**Comment by jkobject** [comment]
Also another Issue is open and ongoing on jkobject/scprint with some information about populate ontologies etc.. 

Please update scdataloader and scprint to their latest version with pip

**Comment by jkobject** [comment]
marking this as closed now
