### ISSUE TITLE
Questions about the downsampling step written in the manuscript.

### ISSUE THREAD

**Issue by HelloWorldLTY** [cantinilab/scPRINT#10]
Hi, thanks for your great work. I have a question about the written content in the manuscript of the downsampling step:

<img width="1179" alt="image" src="https://github.com/user-attachments/assets/923036c7-c658-4c96-94fb-b1dd109d9283">

I am confused about the sampling or possion distribution implemntion. Here you mentioned that r is set as 0.55, which is the dropout rate. However, in the possion distribution implementation, you metnioned that x_i*r*0.55 is treated as center lamba. I think you mean a possion distribution centralized by x_i, is it correct? Moreover, the mask ratio, r, should have a probability like 0.55, so the identity matrix should follow a bernulli distribution with prob=0.55 for 1. Is it correct? Thanks.

**Comment by jkobject** [comment]
Hello @HelloWorldLTY 

Sorry I am only seeing this now. 

Here the poisson lambda is x_i * r * 0.55 where the dropout rate is r
I don't set it to 0.55, 0.55 is just a scaling value. you can find it in the .yml training files and it is often set to 0.6.

the mask ratio is r * 0.55 so the probability for a r=0.5 is around 0.3 meaning ⅓ of the genes are set to 0. Meaning the matrix follows a bernoulli distribution with prob ~0.7.

(but I shouldn't call it a mask as masking and setting to 0 is quite different).

**Comment by HelloWorldLTY** [comment]
Yes thanks, it helps me a lot. The bernoulli distribution for masking makes sense.
