### ISSUE TITLE
Unable to increase cell size in expr_pred output

### ISSUE THREAD

**Issue by JeelPatel98** [cantinilab/scPRINT#5]
I have been using the `Denoiser` with the following parameters:
 
```
model = scPrint.load_from_checkpoint(ckpt_path, precpt_gene_emb=None, transformer="normal")
dn = Denoiser(
    plot_corr_size=10,
    batch_size=2,
    num_workers=1,
    max_len=2500,
    downsample=0.3,
    predict_depth_mult=3,
    dtype=torch.float32,
)
metrics, random_indices, genes, expr_pred = dn(
    model=model,
    adata=adata,
)

```

My subsetted data (input data) has shape (3232, 33097), and the `expr_pred` has shape (10, 1432).  
`expr_pred` output always has only 10 cells even though I've tried increasing the batch size and adjusting other parameters, but the number of cells in the output remains the same. I have tried using all three models: medium, large, and o2uniqsx, but the issue persists across all of them.

After denoising, I expected the `expr_pred` output to contain at least 500 - 800 cells.

Any help or guidance on how to increase the cell size in the `expr_pred` output would be greatly appreciated.

**Comment by jkobject** [comment]
Hello @JeelPatel98,

Sorry for the delay in reaching back! the plot_corr_size parameter is what you are looking for. You should set it to a super high value.
