### ISSUE TITLE
Installing v1.6.0

### ISSUE THREAD

**Issue by lazappi** [cantinilab/scPRINT#8]
I'm trying to try out v1.6.0 but it's not available from PyPI (currently has v1.1.4). Do you plan to make release it there? If not, could you make it possible to install from GitHub with `pip` using `pip install git+https://github.com/cantinilab/scPRINT.git`? Currently it fails with `fatal: No url found for submodule path 'src/triton' in .gitmodules`. I think you would just need to add something to the `.gitmodules` file so hopefully an easy fix. Thanks!

**Comment by jkobject** [comment]
Hello, 

Sorry for the delay but I was away last week. 

I made a big mess before leaving with releases that were completely broken. I will remove them and manage to publish a working release v1.6.1.

In any case whenever you have such an issue please use the latest git version :)

**Comment by jkobject** [comment]
let me know if it works with you now

**Comment by lazappi** [comment]
I just tried in a new environment and I think it worked. It took `pip` a long time to work out which packages versions to use though so maybe those could be defined somewhere?

The output from `pip` shows `scprint-1.6.2` but `scprint.__version__` gives `0.0.1` which had me confused for a while. Maybe that also needs to be set somewhere.

**Comment by jkobject** [comment]
Hello, Thanks for the feedback. 

Let me know how things are going now. 

Best,

**Comment by lazappi** [comment]
I've been able to install things and it seems to be working. I think you can close this now. Thanks for your help!

**Comment by jkobject** [comment]
Hey, also make sure you update to the latest version as I pushed an important debug (it concerns only the smaller model sizes).
